### ISSUE TITLE
Update Godwoken Explorer URL

### ISSUE THREAD

**Issue by Flouse** [godwokenrises/godwoken-doc#160]
The current community explorer for Godwoken at https://gw-mainnet-explorer.nervosdao.community/ is returning a 502 error, indicating that it may be down or experiencing issues. Additionally, there are concerns that the explorer may lack maintenance, which could make it difficult for users to interact with community explorers of Godwoken testnet and mainnet.

To address these issues, we propose GwScan as the default explorer, which is a more robust and actively maintained explorer by [Magickbase team](https://github.com/Magickbase/godwoken_explorer). This would provide users with a better experience and help ensure the stability and reliability of the network.

### Proposed Solution
- [x] Update all the Godwoken explorer URLs to GwScan, which can be found at https://docs.godwoken.io/connectionInfo 

- [x] https://sourcegraph.com/search?q=explorer.nervosdao.community&groupBy=repo
   - [ ] Update ethereum/sourcify
     - https://sourcegraph.com/github.com/ethereum/sourcify/-/blob/src/sourcify-chains.ts?L515:27
     - https://sourcegraph.com/github.com/ethereum/sourcify/-/blob/src/sourcify-chains.ts?L507:27
     - https://sourcegraph.com/github.com/ethereum/sourcify/-/blob/src/chains.json?L13632:36
     - https://sourcegraph.com/github.com/ethereum/sourcify/-/blob/src/chains.json?L13609:36
  - [x] udpate ethereum-lists 
  - [x] Update anyswap/anyswap-crosschain
- [x] search all the docs in godwokenrises org and fix them

**Comment by Flouse** [comment]
> * udpate ethereum-lists
> * [x]  Update anyswap/anyswap-crosschain
> * [x]  search all the docs in godwokenrises org and fix them

@lee920217 Please link the PRs to this issue, thanks.

## Reference
- https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by lee920217** [comment]
> > * udpate ethereum-lists
> > * [x]   Update anyswap/anyswap-crosschain
> > * [x]   search all the docs in godwokenrises org and fix them
> 
> @lee920217 Please link the PRs to this issue, thanks.
> 
> ## Reference
> * https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

OK Flouse,  here are these two PR links.

- https://github.com/ethereum-lists/chains/pull/2757
- https://github.com/anyswap/anyswap-crosschain/pull/14
